### PR TITLE
Add debug logger for http request/response

### PR DESCRIPTION
**Pull request by jhlee-mitre**
Added Ruby built-in logger. By default it is deactivated and can be turned on by changing `logger.level`.

Added two debug msg: http request/response whenever invoked.

### CODE REVIEW

**Review by Jack-Fraser16 — COMMENTED** [review]
This is a good approach! I'm going to open up a PR refactoring how messages are output on the command line, and I think what you're doing here will tie in with that. So, I'm going to keep this PR open until that message refactor is merged in. Then, you can integrate these changes.

**Comment by jhlee-mitre** [comment]
Sounds like a good plan to avoid conflict. I will add some more useful info into debug_logger meanwhile.

**Comment by Jack-Fraser16** [comment]
@jhlee-mitre thoughts on updating this branch now that MessageHandler updates merged in?

**Comment by jhlee-mitre** [comment]
@Jack-Fraser16 Since the MessageHandler already gives the action level information, I don't think the debugger provides additional value for now. And it's an easy add, don't even have to be in production code, can put in dev adhoc as needed. I'm fine either to merge into now or archive PR and come back when we need debugger.

**Comment by Jack-Fraser16** [comment]
@jhlee-mitre Let's close this PR. I think we can add in a "debug" level into the message_handler, but that would be beyond the scope of this -- and at this point having this PR open is confusing. Sorry for late follow-up.

**Comment by jhlee-mitre** [comment]
> @jhlee-mitre Let's close this PR. I think we can add in a "debug" level into the message_handler, but that would be beyond the scope of this -- and at this point having this PR open is confusing. Sorry for late follow-up.

I agree. The engine already provides good level of details from execution. I will close this.

**Pull request closed without merging**
